CREATE SEQUENCE IF NOT EXISTS product_id_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE app_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_app_users PRIMARY KEY (id)
);

CREATE TABLE product_types
(
    id   BIGINT       NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_product_types PRIMARY KEY (id)
);

CREATE TABLE products
(
    id               BIGINT           NOT NULL,
    name             VARCHAR(255)     NOT NULL,
    product_type_id  BIGINT,
    quantity         DOUBLE PRECISION NOT NULL,
    quantity_unit_id BIGINT,
    stored_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    expiry_date      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    image_url        VARCHAR(255),
    image_id         VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE quantity_types
(
    id   BIGINT       NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_quantity_types PRIMARY KEY (id)
);

ALTER TABLE app_users
    ADD CONSTRAINT uc_app_users_username UNIQUE (username);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_PRODUCT_TYPE FOREIGN KEY (product_type_id) REFERENCES product_types (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_QUANTITY_UNIT FOREIGN KEY (quantity_unit_id) REFERENCES quantity_types (id);

INSERT INTO app_users(username, password, role)
VALUES ('coredump-admin', '$2a$10$gOP2I6CCTj2sR96q0t2ESejm4ge4vVtZcWHAdWnMkfWbztEdpNRmC', 'ADMIN');

INSERT INTO product_types VALUES (1, 'FRUITS');
INSERT INTO product_types VALUES (2, 'VEGETABLES');

INSERT INTO quantity_types VALUES (1, 'KILOGRAM');
INSERT INTO quantity_types VALUES (2, 'LITER');
INSERT INTO quantity_types VALUES (3, 'PIECE');